version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my
    environment:
      POSTGRES_USER: wgtoooa     # Логин
      POSTGRES_PASSWORD: 12345  # Пароль
      POSTGRES_DB: URLDB         # Название БД
    ports:
      - "5432:5432"             # Порт (host:container)
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: