version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: my_postgres
    environment:
      POSTGRES_USER: admin      # Логин
      POSTGRES_PASSWORD: secret  # Пароль
      POSTGRES_DB: mydb         # Название БД
    ports:
      - "5432:5432"             # Порт (host:container)
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: